plugins {
	id "fabric-loom" version "1.14.+"
	id "com.modrinth.minotaur" version "2.+"
}

version = "2.7.0.3"
group = "com.modrinth.minotaur"

dependencies {
	minecraft "com.mojang:minecraft:1.17.1"
	mappings "net.fabricmc:yarn:1.17.1+build.65:v2"
	modImplementation "net.fabricmc:fabric-loader:0.12.12"
}

java.withSourcesJar()
java.withJavadocJar()

import com.modrinth.minotaur.dependencies.DependencyType
import com.modrinth.minotaur.dependencies.ModDependency
import com.modrinth.minotaur.dependencies.VersionDependency

modrinth {
	projectId = "allergies"
	uploadFile = remapJar
	additionalFiles = [project.file("build/devlibs/loom-$version-dev.jar")]
	additionalFiles {
		sourcesJar sourcesJar
		javadocJar javadocJar
		other 'build/loom-cache/remapped_working/remapped.net.fabricmc-fabric-loader-2b40239f-0.12.12.jar'
	}
	versionType = "alpha"
	dependencies = [
		new ModDependency("test-project", "optional"),
		new VersionDependency("dG06oDvH", DependencyType.INCOMPATIBLE)
	]
	dependencies {
		required.project "corrupted"
		optional.version "9MsDOrJE"
		incompatible.version "AANobbMI", "mc1.21.11-0.8.2-fabric"
		embedded.project "uiW75cBG"
		required.version "modmenu", "11.0.2"
	}
	//debugMode = true
}

tasks.withType(Jar) {
	manifest {
		attributes([
				'Timestamp': System.currentTimeMillis(),
		])
	}
}
