name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17 # Use Java 17 here because the Loom test env needs it
          distribution: temurin

      - name: Cache Gradle files
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*/build.gradle', '*/settings.gradle', '*gradle.*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build publishToMavenLocal
        env:
          EXCLUDE_SUBPROJECTS: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: Artifacts
          path: build/libs

      - name: Test with Gradle
        run: ./gradlew fg:modrinth loom:modrinth
        if: ${{ !contains(github.event.head_commit.message, 'skip test') }}
        env:
          MODRINTH_TOKEN: dummy_token_for_CI
